admin:
  mobile_phone: '18691874026'
  pwd: '12345678'
  reg_name: admin
  type: 0
browser:
  mobile_phone: '18685967132'
  pwd: '12345678'
  reg_name: browser
  type: 1
investor:
  mobile_phone: '18669754203'
  pwd: '12345678'
  reg_name: investor
  type: 1
